---
apiVersion: "extensions/v1beta1"
kind: "ReplicaSet"
metadata:
  annotations:
    service.spinnaker.io/enabled: "true"
  finalizers: []
  labels:
    app: "celestial"
    celestial-staging-v007: "true"
    cluster: "celestial-staging"
    load-balancer-celestial-staging: "true"
    replication-controller: "celestial-staging-v007"
    stack: "staging"
    version: "6"
  name: "celestial-staging-v007"
  namespace: "default"
  ownerReferences: []
spec:
  replicas: 3
  selector:
    matchExpressions: []
    matchLabels:
      app: "celestial"
      celestial-staging-v007: "true"
      cluster: "celestial-staging"
      replication-controller: "celestial-staging-v007"
      stack: "staging"
      version: "6"
  template:
    metadata:
      finalizers: []
      labels:
        app: "celestial"
        celestial-staging-v007: "true"
        cluster: "celestial-staging"
        load-balancer-celestial-staging: "true"
        replication-controller: "celestial-staging-v007"
        stack: "staging"
        version: "6"
      ownerReferences: []
    spec:
      containers:
      - args: []
        command: []
        env: []
        envFrom: []
        image: "gcr.io/river-direction-210022/blue-green:afb4184182230fa7e46d26ded521906c8b5b8774"
        imagePullPolicy: "IfNotPresent"
        name: "river-direction-210022-blue-green"
        ports:
        - containerPort: 80
          name: "http"
          protocol: "TCP"
        resources:
          requests:
            cpu: "10m"
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: "File"
        volumeMounts: []
      dnsPolicy: "ClusterFirst"
      hostAliases: []
      imagePullSecrets:
      - name: "gcr-registry"
      initContainers: []
      restartPolicy: "Always"
      schedulerName: "default-scheduler"
      securityContext:
        supplementalGroups: []
      terminationGracePeriodSeconds: 30
      tolerations: []
      volumes: []
